### ISSUE TITLE
how to install 'arch-chroot'? can't find anthing about it.

### ISSUE THREAD

**Issue by Itai-Nelken** [SpacingBat3/box86-appimage#1]
I'm trying to build a appimage of the newest box86 on manjaro ARM on pi4 using your script, but it tells me I need 'arch-chroot'. I searched but didn't find anything about arch-chroot.
sorry if this is a stupid question.

**Comment by SpacingBat3** [comment]
> I'm trying to build a appimage of the newest box86 on manjaro ARM on pi4 using your script, but it tells me I need 'arch-chroot'. I searched but didn't find anything about arch-chroot.

You probably haven't searched in `pacman`:
```
pacman -F arch-chroot
```
(I'm not going to spoil you the results, execute it yourself to find out what it does :wink:)
> sorry if this is a stupid question.

Yea, managing packages might not be easy for the beginner/novice arch users, but it's great anyway you have entered this issue – some other people might have that issue like you. However, it would be more appreciated to ask these sort of questions in the [Discussions](https://github.com/SpacingBat3/box86-appimage/discussions) next time.

**Comment by Itai-Nelken** [comment]
Thanks! I had tried `pacman -Ss arch-chroot` (I found that on some pacman tutorial), and it didn't work.

**Comment by SpacingBat3** [comment]
@Itai-Nelken Also see this commit: ed61f35.
