### ISSUE TITLE
error while copying libraries

### ISSUE THREAD

**Issue by Itai-Nelken** [SpacingBat3/box86-appimage#2]
```bash
Select the method on which libraries are copied: 
1) Copy all files.
2) Copy ".so" libraries.
3) Copy only necessary libraries.
Enter number: 1

Copying the `/lib` content from the current chroot...
ERROR: An error occured while copying libraries from the current chroot!

Press any key to continue.
```

**Comment by SpacingBat3** [comment]
> ```shell
> Select the method on which libraries are copied: 
> 1) Copy all files.
> 2) Copy ".so" libraries.
> 3) Copy only necessary libraries.
> Enter number: 1
> 
> Copying the `/lib` content from the current chroot...
> ERROR: An error occured while copying libraries from the current chroot!
> 
> Press any key to continue.
> ```

I'll probably archive this project soon – in the future, I will work on better solutions than that.
